##### 추가된 역할: Nginx 및 Tomcat 설정 ###
---
- name: Install required Ansible roles
  hosts: localhost
  tasks:
    - name: Install nginx role
      ansible.builtin.command:
        cmd: ansible-galaxy install nginxinc.nginx

- hosts: web
  become: yes
  roles:
    - nginx

- hosts: was
  become: yes
  roles:
    - tomcat

# - name: Deploy Tomcat and Nginx
#  hosts: all
#  become: yes
#  roles:
#    - { role: tomcat, when: "'was' in group_names" }
#    - { role: nginx, when: "'web' in group_names" }

#####