- name: install jdk, tar
  apt:
    name:
      - openjdk-11-jdk
      - tar
    state: present
    update_cache: true

- name: "download {{ package }}"
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz"
    dest: /tmp
  notify: start tomcat

- name: unarchive tomcat
  ansible.builtin.unarchive:
    src: /tmp/apache-tomcat-9.0.71.tar.gz
    dest: /opt
    remote_src: yes
  notify: start tomcat