---
# tasks file for tomcat
- name: install jdk, tar
  yum:
    name: 
      - java-11-openjdk
      - tar
    state: present

- name: "download {{ package }}"
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz"
    dest: ./
  notify: firewall open tomcat

- name: unarchive tomcat
  unarchive:
    src: ./apache-tomcat-9.0.71.tar.gz
    dest: ./
    remote_src: yes
  notify: started tomcat

#- name: index.jsp copy
#  copy:
#    src: index.jsp
#    dest: /root/apache-tomcat-9.0.71/webapps/ROOT/index.jsp
#    owner: root
#    group: root
#    remote_src: yes
#
#- name: server.xml copy
#  template:
#    src: server.xml.j2
#    dest: ./apache-tomcat-9.0.71/conf/server.xml
#    owner: root
#    group: root
#    remote_src: yes
#  notify: started tomcat
