- name: "install {{ package }}"
  apt:
    name: "{{ package }}"
    state: present
  notify:
    - started nginx

- name: index.html copy
  copy:
    src: index.html
    dest: /usr/share/nginx/html
    owner: nginx
    group: nginx

- name: template copy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
  notify: restarted nginx